#!/bin/bash

# Check if python is installed
if ! command -v python3 &> /dev/null; then
    echo "Python3 is not installed. Installing..."
    exit 1
fi

# Check if pip is installed
if ! command -v pip3 &> /dev/null; then
    echo "pip3 is not installed. Installing..."
    exit 1
fi

# Install dependencies
echo "Installing Python dependencies..."
pip3 install -r requirements.txt

# Run game
echo "Executing main.py..."
python3 main.py